### ISSUE TITLE
Domain Exploration

### ISSUE THREAD

**Issue by ASingh082** [UC-Irvine-CS175/final-project-brie-lliant-clusters#3]
#### Main Goals
- Explore the dataset/domain 
- Explore pre-trained models for K-means
- Find secondary viable model (outside of clustering)

####TODO
- Put links and research in class discord channel for team

**Comment by MehrdokhtNoranian** [comment]
add your useful links that you found in README file

**Comment by MehrdokhtNoranian** [comment]
done
